package com.xyzl.driverphone.model

object MockData {
    val trips = listOf(
        Trip(
            id = "T001",
            date = "今天",
            time = "14:30",
            origin = "吉隆坡国际机场",
            destination = "武吉免登",
            passenger = "张先生",
            whatsapp = "+60 12-345 6789",
            wechat = "zhang_kl",
            adults = 2,
            children = 1,
            luggage = 2,
            fare = 86.00,
            salary = 60.00,
            status = TripStatus.ONGOING,
            pickupTime = "14:42",
            dropoffTime = "—",
        ),
        Trip(
            id = "T002",
            date = "今天",
            time = "15:00",
            origin = "双子塔",
            destination = "谷中城",
            passenger = "李女士",
            whatsapp = "+60 13-222 8888",
            wechat = "li_mm",
            adults = 1,
            children = 0,
            luggage = 1,
            fare = 24.50,
            salary = 17.00,
            status = TripStatus.PENDING,
            pickupTime = "—",
            dropoffTime = "—",
        ),
        Trip(
            id = "T003",
            date = "今天",
            time = "15:20",
            origin = "中央车站",
            destination = "黑风洞",
            passenger = "王先生",
            whatsapp = "+60 16-555 1234",
            wechat = "wang_88",
            adults = 3,
            children = 0,
            luggage = 3,
            fare = 32.00,
            salary = 22.00,
            status = TripStatus.PENDING,
            pickupTime = "—",
            dropoffTime = "—",
        ),
        Trip(
            id = "T004",
            date = "昨天",
            time = "18:40",
            origin = "柏威年广场",
            destination = "蒲种",
            passenger = "林女士",
            whatsapp = "+60 17-999 0000",
            wechat = "lin_88",
            adults = 2,
            children = 2,
            luggage = 3,
            fare = 41.80,
            salary = 29.00,
            status = TripStatus.COMPLETED,
            pickupTime = "18:52",
            dropoffTime = "19:31",
        ),
        Trip(
            id = "T005",
            date = "昨天",
            time = "16:10",
            origin = "茨厂街",
            destination = "孟沙",
            passenger = "陈先生",
            whatsapp = "+60 12-777 3333",
            wechat = "chen_cc",
            adults = 1,
            children = 0,
            luggage = 1,
            fare = 18.60,
            salary = 13.00,
            status = TripStatus.COMPLETED,
            pickupTime = "16:21",
            dropoffTime = "16:48",
        ),
        Trip(
            id = "T006",
            date = "昨天",
            time = "13:55",
            origin = "武吉加里尔",
            destination = "沙登",
            passenger = "黄女士",
            whatsapp = "+60 11-444 6666",
            wechat = "huang_hh",
            adults = 4,
            children = 1,
            luggage = 4,
            fare = 27.40,
            salary = 19.00,
            status = TripStatus.COMPLETED,
            pickupTime = "14:05",
            dropoffTime = "14:37",
        ),
        Trip(
            id = "T007",
            date = "前天",
            time = "20:15",
            origin = "双威金字塔",
            destination = "梳邦",
            passenger = "吴先生",
            whatsapp = "+60 19-888 2222",
            wechat = "wu_ww",
            adults = 2,
            children = 0,
            luggage = 2,
            fare = 35.20,
            salary = 0.00,
            status = TripStatus.CANCELLED,
            pickupTime = "—",
            dropoffTime = "—",
        ),
    )
}
